---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(data.table)
setwd("C:/users/Meso/Documents/Regis/MSDS 692/R code")
```



```{r}
LineTraits <- read.csv('C:\\Users\\Meso\\Documents\\Regis\\MSDS 692\\CSI2015_TRAITS_WITH_LOC.csv', header = TRUE, stringsAsFactors = FALSE, na.strings = c(NA, "NA", " NA"))
LineTraits_norm <- read.csv('C:\\Users\\Meso\\Documents\\Regis\\MSDS 692\\R code\\LINE_TRAITS_NORMALIZED.csv', header = TRUE, stringsAsFactors = FALSE, na.strings = c(NA, 'NA', ' NA'))
```

```{r}
PlotTraits <- read.csv('C:\\Users\\Meso\\Documents\\Regis\\MSDS 692\\CSI2015_PLOT_TRAITS_LOC_NEW.csv', header = TRUE, stringsAsFactors = FALSE, na.strings = c(NA, "NA", " NA"))
PlotTraits_norm <- read.csv('C:\\Users\\Meso\\Documents\\Regis\\MSDS 692\\R code\\PLOT_TRAITS_NORMALIZED.csv', header = TRUE, stringsAsFactors = FALSE, na.strings = c(NA, 'NA', ' NA'))
```


```{r}
exclude_line <- data.frame(Lines = c('CONRAD', 'MERIT 57'))
exclude_trait_nm <- data.frame(Trait_NM = c('UNIT#', 'FILTRATE ONE HOUR', 'MALT PROBLEMS', 'STEEP IN DATE', 'STEEP NUMBER', 'MALTING PROGRAM', 'LODGING'))
Line_Use <- LineTraits %>% filter(! dbo_LINE_LINE_NM %in% exclude_line$Lines, ! TRAIT_NM %in% exclude_trait_nm$Trait_NM)
Plot_Use <- PlotTraits %>% filter(! dbo_LINE_LINE_NM %in% exclude_line$Lines, ! TRAIT_NM %in% exclude_trait_nm$Trait_NM)
```


```{r}
LineTraits_norm$X <- NULL
LineTraits_norm$TRAIT_ID <- NULL
PlotTraits_norm$X <- NULL
LineTraits$TRAIT_ID <- NULL
Line_Use$TRAIT_ID <- NULL
common_atts <- c('dbo_LINE_LINE_ID', 'dbo_LINE_LINE_NM', 'dbo_LINE_1_LINE_ID', 'dbo_LINE_1_LINE_NM',	'TRAIT_NM',	'TRAIT_DSC', 'OBSRV_NT_NBR', 'OBSRV_EFF_TSP', 'CNTRY_NM', 'REGN_NM', 'LOC_NM', 'COOP_LOC_NM')
LineTraits_an <- merge(Line_Use, LineTraits_norm, by = common_atts, all.x = TRUE)
PlotTraits_an <- merge(Plot_Use, PlotTraits_norm, by = common_atts, all.x = TRUE)
common_atts_an <- c('dbo_LINE_LINE_ID', 'dbo_LINE_LINE_NM', 'dbo_LINE_1_LINE_ID', 'dbo_LINE_1_LINE_NM',	'TRAIT_NM',	'TRAIT_DSC', 'OBSRV_NT_NBR', 'OBSRV_EFF_TSP', 'CNTRY_NM', 'REGN_NM', 'LOC_NM', 'COOP_LOC_NM', 'norm_obs')
Traits_hold <- merge(LineTraits_an, PlotTraits_an, by = common_atts_an, all = TRUE)
Traits <- unique(Traits_hold)
```

```{r}
coop_loc <- data.frame(COOP_LOC_NM = as.character(unique(Traits$COOP_LOC_NM)), stringsAsFactors = FALSE)
```

```{r}
Traits$LINEIDLOC <- paste(Traits$dbo_LINE_LINE_ID, Traits$COOP_LOC_NM)
traits_by_line <- dcast(as.data.table(Traits), LINEIDLOC ~ TRAIT_NM, value.var = 'norm_obs', fun.aggregate = mean)
traits_by_line$dbo_LINE_LINE_ID <- character()
traits_by_line$COOP_LOC_NM <- character()
for (i in 1:nrow(traits_by_line)) {
  lineid <- substr(traits_by_line[i,1], 0, 6)
  cooploc <- substr(traits_by_line[i, 1], 8, nchar(traits_by_line[i,1]))
  traits_by_line$dbo_LINE_LINE_ID[i] <- lineid
  traits_by_line$COOP_LOC_NM[i] <- cooploc
}
Traits_hld <- Traits
Traits_hld$TRAIT_NM <- NULL
Traits_hld$TRAIT_DSC <- NULL
Traits_hld$OBSRV_NT_NBR <- NULL
Traits_hld$OBSRV_EFF_TSP <- NULL
Traits_hld$norm_obs <- NULL
Traits_hld$LINEIDLOC <- NULL
traits_by_line$LINEIDLOC <- NULL
Traits_lines <- unique(Traits_hld)
common_atts_ml <- c('dbo_LINE_LINE_ID', 'COOP_LOC_NM')
ML_traits <- merge(Traits_lines, traits_by_line, by = common_atts_ml)

```



```{r}
ML <- read.csv('ML_TRAITS.csv', header = TRUE, stringsAsFactors = FALSE, na.strings = c(NA, 'NA', ' NA', 'NaN', NaN))
```


```{r}

```

